"""
JARVIS Ambient Acoustic Guardian
=================================
Monitors microphone feeds locally for specific environmental triggers:
- Glass breaking detection
- Baby crying detection
- Doorbell ringing
- Smoke alarm / fire alarm
- Dog barking
- Intrusion / loud noise
- Custom sound patterns

All processing is LOCAL — no audio leaves the device.
"""

import os
import io
import json
import time
import struct
import math
import logging
import asyncio
from typing import Dict, Any, Optional, Callable, AsyncGenerator, List
from dataclasses import dataclass, field
from enum import Enum
from collections import deque

log = logging.getLogger("jarvis-acoustic")


class SoundEvent(str, Enum):
    GLASS_BREAKING = "glass_breaking"
    BABY_CRYING = "baby_crying"
    DOORBELL = "doorbell"
    SMOKE_ALARM = "smoke_alarm"
    DOG_BARKING = "dog_barking"
    LOUD_NOISE = "loud_noise"
    SILENCE = "silence"
    SPEECH = "speech"
    MUSIC = "music"
    UNKNOWN = "unknown"


class AlertPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class SoundPattern:
    """A detected sound pattern."""
    event: str
    confidence: float
    timestamp: float
    duration_ms: float
    rms_level: float
    frequency_dominant: float
    priority: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AcousticAlert:
    """An alert generated by the acoustic guardian."""
    alert_id: str
    event: str
    priority: str
    confidence: float
    timestamp: float
    message: str
    acknowledged: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GuardianConfig:
    """Configuration for the acoustic guardian."""
    enabled: bool = True
    sample_rate: int = 16000
    chunk_size: int = 4096
    analysis_window_ms: int = 500
    loud_noise_threshold_db: float = 80.0
    monitoring_events: List[str] = field(default_factory=lambda: [
        "glass_breaking", "baby_crying", "doorbell",
        "smoke_alarm", "dog_barking", "loud_noise",
    ])
    cooldown_seconds: float = 10.0
    max_alerts_per_hour: int = 20


class SoundAnalyzer:
    """
    Lightweight audio feature extraction for sound event detection.
    Uses energy analysis, spectral features, and pattern matching.
    """

    def __init__(self, sample_rate: int = 16000):
        self.sample_rate = sample_rate
        self._energy_history = deque(maxlen=100)
        self._silence_threshold = 0.005

    def extract_features(self, audio_chunk: bytes) -> Dict[str, float]:
        """Extract audio features from a PCM chunk."""
        if len(audio_chunk) < 2:
            return {"rms": 0, "zcr": 0, "spectral_centroid": 0, "silence_ratio": 1.0}

        samples = struct.unpack(f"<{len(audio_chunk) // 2}h", audio_chunk)
        if not samples:
            return {"rms": 0, "zcr": 0, "spectral_centroid": 0, "silence_ratio": 1.0}

        # RMS energy
        sum_squares = sum(s * s for s in samples)
        rms = (sum_squares / len(samples)) ** 0.5 / 32768.0

        # Zero-crossing rate
        crossings = sum(
            1 for i in range(1, len(samples))
            if (samples[i] >= 0) != (samples[i - 1] >= 0)
        )
        zcr = crossings / len(samples)

        # Spectral centroid estimation (simplified via autocorrelation)
        spectral_centroid = self._estimate_spectral_centroid(samples)

        # Silence ratio
        silent_count = sum(1 for s in samples if abs(s) < 32768 * self._silence_threshold)
        silence_ratio = silent_count / len(samples)

        # RMS in dB
        rms_db = 20 * math.log10(max(rms, 1e-10))

        # Energy history for burst detection
        self._energy_history.append(rms)
        avg_energy = sum(self._energy_history) / len(self._energy_history) if self._energy_history else 0
        energy_ratio = rms / max(avg_energy, 1e-10)

        return {
            "rms": rms,
            "rms_db": rms_db,
            "zcr": zcr,
            "spectral_centroid": spectral_centroid,
            "silence_ratio": silence_ratio,
            "energy_ratio": energy_ratio,
        }

    def _estimate_spectral_centroid(self, samples: tuple) -> float:
        """Estimate spectral centroid via zero-crossing rate approximation."""
        if len(samples) < 2:
            return 0.0

        # Simple approximation using sign changes
        sign_changes = 0
        for i in range(1, len(samples)):
            if (samples[i] >= 0) != (samples[i - 1] >= 0):
                sign_changes += 1

        # Approximate frequency from zero crossings
        freq_est = (sign_changes / (2 * len(samples))) * self.sample_rate
        return min(freq_est, self.sample_rate / 2)

    def classify_sound(self, features: Dict[str, float]) -> SoundEvent:
        """Classify sound based on extracted features."""
        rms = features.get("rms", 0)
        rms_db = features.get("rms_db", -60)
        zcr = features.get("zcr", 0)
        spectral_centroid = features.get("spectral_centroid", 0)
        silence_ratio = features.get("silence_ratio", 1.0)
        energy_ratio = features.get("energy_ratio", 1.0)

        # Silence detection
        if silence_ratio > 0.9 or rms < 0.001:
            return SoundEvent.SILENCE

        # Smoke alarm: high-pitched, periodic, high energy
        if rms_db > 70 and spectral_centroid > 3000 and zcr > 0.15:
            return SoundEvent.SMOKE_ALARM

        # Glass breaking: high energy burst, high frequency, short duration
        if rms_db > 75 and energy_ratio > 3.0 and spectral_centroid > 2000:
            return SoundEvent.GLASS_BREAKING

        # Baby crying: sustained mid-frequency energy, periodic
        if 30 < rms_db < 75 and 200 < spectral_centroid < 1500 and zcr > 0.05:
            return SoundEvent.BABY_CRYING

        # Doorbell: two-tone pattern, mid energy
        if 50 < rms_db < 75 and 500 < spectral_centroid < 2000:
            return SoundEvent.DOORBELL

        # Dog barking: burst pattern, mid-low frequency
        if rms_db > 55 and 200 < spectral_centroid < 1500 and energy_ratio > 2.0:
            return SoundEvent.DOG_BARKING

        # Loud noise
        if rms_db > 75:
            return SoundEvent.LOUD_NOISE

        # Speech
        if 0.02 < zcr < 0.3 and 200 < spectral_centroid < 4000:
            return SoundEvent.SPEECH

        return SoundEvent.UNKNOWN


class AcousticGuardian:
    """
    Ambient Acoustic Guardian — always-on environmental sound monitoring.
    
    Runs locally with zero cloud dependency. Processes audio in real-time
    and generates alerts for specific sound events.
    """

    def __init__(self, config: Optional[GuardianConfig] = None):
        self._config = config or GuardianConfig()
        self._analyzer = SoundAnalyzer(self._config.sample_rate)
        self._alerts: List[AcousticAlert] = None
        self._alert_counter = 0
        self._last_event_times: Dict[str, float] = {}
        self._hourly_alert_count = 0
        self._hour_start = time.time()
        self._callbacks: List[Callable] = []
        self._recent_events = deque(maxlen=50)

    def _reset_hourly_count(self):
        """Reset hourly alert counter."""
        now = time.time()
        if now - self._hour_start > 3600:
            self._hourly_alert_count = 0
            self._hour_start = now

    def on_alert(self, callback: Callable[[AcousticAlert], None]):
        """Register a callback for sound alerts."""
        self._callbacks.append(callback)

    async def process_audio_stream(
        self,
        audio_stream: AsyncGenerator[bytes, None],
    ) -> AsyncGenerator[AcousticAlert, None]:
        """
        Process a continuous audio stream for environmental sound detection.
        Yields AcousticAlert when specific sounds are detected.
        """
        buffer = b""
        required_bytes = self._config.chunk_size * 2  # 16-bit PCM

        async for chunk in audio_stream:
            if not self._config.enabled:
                continue

            buffer += chunk

            while len(buffer) >= required_bytes:
                audio_chunk = buffer[:required_bytes]
                buffer = buffer[required_bytes:]

                alert = self._analyze_chunk(audio_chunk)
                if alert:
                    # Notify callbacks
                    for cb in self._callbacks:
                        try:
                            cb(alert)
                        except Exception:
                            pass
                    yield alert

    def _analyze_chunk(self, audio_chunk: bytes) -> Optional[AcousticAlert]:
        """Analyze a single audio chunk and generate alert if needed."""
        features = self._analyzer.extract_features(audio_chunk)
        event = self._analyzer.classify_sound(features)

        # Only alert for monitored events
        if event.value not in self._config.monitoring_events:
            return None

        # Cooldown check
        now = time.time()
        last_time = self._last_event_times.get(event.value, 0)
        if now - last_time < self._config.cooldown_seconds:
            return None

        # Hourly limit check
        self._reset_hourly_count()
        if self._hourly_alert_count >= self._config.max_alerts_per_hour:
            return None

        # Determine priority
        priority = self._determine_priority(event, features)

        # Calculate confidence
        confidence = self._calculate_confidence(event, features)

        # Only alert above threshold
        if confidence < 0.4:
            return None

        # Create alert
        self._alert_counter += 1
        alert_id = f"acoustic_{int(now)}_{self._alert_counter}"

        alert = AcousticAlert(
            alert_id=alert_id,
            event=event.value,
            priority=priority.value,
            confidence=confidence,
            timestamp=now,
            message=self._generate_alert_message(event, features, confidence),
            metadata={
                "rms_db": round(features.get("rms_db", 0), 1),
                "spectral_centroid": round(features.get("spectral_centroid", 0), 1),
                "zcr": round(features.get("zcr", 0), 4),
            },
        )

        self._last_event_times[event.value] = now
        self._hourly_alert_count += 1
        self._recent_events.append({
            "event": event.value,
            "timestamp": now,
            "confidence": confidence,
            "priority": priority.value,
        })

        log.info(f"ACOUSTIC GUARDIAN: {event.value} detected (confidence={confidence:.2f}, priority={priority.value})")

        return alert

    def _determine_priority(self, event: SoundEvent, features: Dict[str, float]) -> AlertPriority:
        """Determine alert priority based on event type and audio features."""
        priority_map = {
            SoundEvent.SMOKE_ALARM: AlertPriority.CRITICAL,
            SoundEvent.GLASS_BREAKING: AlertPriority.HIGH,
            SoundEvent.BABY_CRYING: AlertPriority.HIGH,
            SoundEvent.DOORBELL: AlertPriority.MEDIUM,
            SoundEvent.DOG_BARKING: AlertPriority.LOW,
            SoundEvent.LOUD_NOISE: AlertPriority.MEDIUM,
        }
        return priority_map.get(event, AlertPriority.LOW)

    def _calculate_confidence(self, event: SoundEvent, features: Dict[str, float]) -> float:
        """Calculate detection confidence based on features."""
        rms_db = features.get("rms_db", -60)
        energy_ratio = features.get("energy_ratio", 1.0)
        spectral = features.get("spectral_centroid", 0)

        base_confidence = 0.5

        # Boost confidence based on energy
        if rms_db > 70:
            base_confidence += 0.2
        elif rms_db > 50:
            base_confidence += 0.1

        # Boost for burst detection
        if energy_ratio > 2.0:
            base_confidence += 0.15

        # Event-specific adjustments
        if event == SoundEvent.SMOKE_ALARM and spectral > 3000:
            base_confidence += 0.15
        elif event == SoundEvent.GLASS_BREAKING and energy_ratio > 3.0:
            base_confidence += 0.1

        return min(base_confidence, 1.0)

    def _generate_alert_message(
        self,
        event: SoundEvent,
        features: Dict[str, float],
        confidence: float,
    ) -> str:
        """Generate a human-readable alert message."""
        messages = {
            SoundEvent.GLASS_BREAKING: "Glass breaking detected! Possible window intrusion.",
            SoundEvent.BABY_CRYING: "Baby crying detected. Attention needed.",
            SoundEvent.DOORBELL: "Doorbell detected. Someone may be at the door.",
            SoundEvent.SMOKE_ALARM: "SMOKE ALARM triggered! Check for fire immediately.",
            SoundEvent.DOG_BARKING: "Dog barking detected in the environment.",
            SoundEvent.LOUD_NOISE: "Unusually loud noise detected.",
        }
        base_msg = messages.get(event, f"Sound event: {event.value}")
        return f"{base_msg} (Confidence: {confidence:.0%})"

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in (self._alerts or []):
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def get_recent_events(self, limit: int = 20) -> List[Dict[str, Any]]:
        """Get recent sound events."""
        return list(self._recent_events)[-limit:]

    def get_stats(self) -> Dict[str, Any]:
        """Get acoustic guardian statistics."""
        event_counts = {}
        for event in self._recent_events:
            e = event["event"]
            event_counts[e] = event_counts.get(e, 0) + 1
        return {
            "enabled": self._config.enabled,
            "monitored_events": self._config.monitoring_events,
            "total_events_detected": len(self._recent_events),
            "event_distribution": event_counts,
            "hourly_alert_count": self._hourly_alert_count,
            "cooldown_seconds": self._config.cooldown_seconds,
        }


# ── Singleton ────────────────────────────────────────────────────────────
_guardian: Optional[AcousticGuardian] = None


def get_acoustic_guardian() -> AcousticGuardian:
    global _guardian
    if _guardian is None:
        _guardian = AcousticGuardian()
    return _guardian
