"""
Incident Templates — Post-mortem, security audit, CVE advisory, and executive report templates.

Generates structured HTML documents for incident response communications.
"""

import time
import logging
from typing import Dict, List, Optional
from pathlib import Path

log = logging.getLogger("jarvis-incidents")


def postmortem_html(data: Dict) -> str:
    """Generate an incident post-mortem HTML document.
    
    data keys: title, incident_id, severity, date_detected, date_resolved,
               duration, impact, root_cause, timeline, affected_services,
               resolution, action_items, metrics
    """
    timeline_rows = ""
    for item in data.get("timeline", []):
        timeline_rows += f"""<tr>
<td>{item.get('time', '')}</td>
<td>{item.get('event', '')}</td>
<td>{item.get('actor', 'System')}</td>
</tr>"""

    actions_html = ""
    for item in data.get("action_items", []):
        owner = item.get("owner", "Unassigned")
        priority = item.get("priority", "medium")
        color = {"critical": "#ef4444", "high": "#f59e0b", "medium": "#3b82f6", "low": "#64748b"}.get(priority, "#3b82f6")
        actions_html += f"""<div class="action-item">
<span class="priority" style="background:{color}">{priority.upper()}</span>
<span class="action-text">{item.get('description', '')}</span>
<span class="owner">{owner}</span>
</div>"""

    services_html = "".join(f'<span class="tag">{s}</span>' for s in data.get("affected_services", []))

    metrics = data.get("metrics", {})
    metrics_html = ""
    if metrics:
        metrics_html = '<div class="stats">'
        for k, v in metrics.items():
            metrics_html += f'<div class="stat"><div class="stat-value">{v}</div><div class="stat-label">{k}</div></div>'
        metrics_html += '</div>'

    severity = data.get("severity", "P2")
    sev_color = {"P0": "#ef4444", "P1": "#f59e0b", "P2": "#3b82f6", "P3": "#64748b"}.get(severity, "#3b82f6")

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Post-Mortem: {data.get('title', 'Incident')}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'Segoe UI',system-ui; background:#0f172a; color:#e2e8f0; padding:32px; max-width:900px; margin:0 auto; }}
h1 {{ font-size:1.8em; margin-bottom:8px; }}
.severity {{ display:inline-block; padding:4px 12px; border-radius:6px; color:white; font-weight:700; background:{sev_color}; }}
.meta {{ color:#94a3b8; margin:12px 0 24px; font-size:0.9em; }}
h2 {{ color:#60a5fa; margin:24px 0 12px; font-size:1.1em; border-bottom:1px solid #1e293b; padding-bottom:6px; }}
table {{ width:100%; border-collapse:collapse; margin:12px 0; }}
th {{ text-align:left; padding:10px; background:#1e293b; color:#94a3b8; }}
td {{ padding:10px; border-bottom:1px solid #1e293b; }}
.tags {{ display:flex; gap:6px; flex-wrap:wrap; margin:8px 0; }}
.tag {{ background:#1e293b; padding:3px 10px; border-radius:4px; font-size:0.8em; color:#94a3b8; }}
.stats {{ display:flex; gap:16px; margin:12px 0; }}
.stat {{ background:#1e293b; padding:16px; border-radius:8px; text-align:center; flex:1; }}
.stat-value {{ font-size:1.6em; font-weight:700; color:#60a5fa; }}
.stat-label {{ font-size:0.75em; color:#64748b; margin-top:4px; }}
.action-item {{ display:flex; align-items:center; gap:10px; padding:10px; background:#1e293b; border-radius:6px; margin:6px 0; }}
.priority {{ padding:2px 8px; border-radius:4px; font-size:0.7em; font-weight:700; color:white; }}
.action-text {{ flex:1; }}
.owner {{ color:#64748b; font-size:0.85em; }}
.section {{ margin:16px 0; line-height:1.6; color:#cbd5e1; }}
</style></head><body>
<h1>{data.get('title', 'Incident Post-Mortem')}</h1>
<div class="meta">
<span class="severity">{severity}</span> &nbsp;
Incident ID: {data.get('incident_id', 'N/A')} |
Detected: {data.get('date_detected', 'N/A')} |
Duration: {data.get('duration', 'N/A')}
</div>

<h2>Impact</h2>
<div class="section">{data.get('impact', 'No impact assessment available.')}</div>

<h2>Affected Services</h2>
<div class="tags">{services_html}</div>

{metrics_html}

<h2>Root Cause</h2>
<div class="section">{data.get('root_cause', 'Under investigation.')}</div>

<h2>Timeline</h2>
<table><thead><tr><th>Time</th><th>Event</th><th>Actor</th></tr></thead>
<tbody>{timeline_rows}</tbody></table>

<h2>Resolution</h2>
<div class="section">{data.get('resolution', 'Pending.')}</div>

<h2>Action Items</h2>
{actions_html}

<div class="meta" style="margin-top:32px">
Generated by JARVIS | {time.strftime('%Y-%m-%d %H:%M UTC')}
</div>
</body></html>"""


def security_advisory_html(data: Dict) -> str:
    """Generate a CVE/security advisory HTML document.
    
    data keys: cve_id, title, severity, affected_products, affected_versions,
               description, impact, remediation, references, discovery_date
    """
    products_html = "".join(f'<tr><td>{p.get("name","")}</td><td>{p.get("versions","")}</td><td>{p.get("fixed_in","N/A")}</td></tr>'
                           for p in data.get("affected_products", []))
    refs_html = "".join(f'<li><a href="{r}" style="color:#60a5fa">{r}</a></li>' for r in data.get("references", []))

    severity = data.get("severity", "HIGH")
    sev_color = {"CRITICAL": "#ef4444", "HIGH": "#f59e0b", "MEDIUM": "#3b82f6", "LOW": "#64748b"}.get(severity, "#3b82f6")

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Security Advisory: {data.get('cve_id', '')}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'Segoe UI',system-ui; background:#0f172a; color:#e2e8f0; padding:32px; max-width:900px; margin:0 auto; }}
h1 {{ font-size:1.6em; margin-bottom:8px; }}
.severity {{ display:inline-block; padding:4px 12px; border-radius:6px; color:white; font-weight:700; background:{sev_color}; }}
h2 {{ color:#60a5fa; margin:20px 0 10px; font-size:1em; border-bottom:1px solid #1e293b; padding-bottom:6px; }}
table {{ width:100%; border-collapse:collapse; margin:10px 0; }}
th {{ text-align:left; padding:8px; background:#1e293b; color:#94a3b8; }}
td {{ padding:8px; border-bottom:1px solid #1e293b; }}
.section {{ line-height:1.6; color:#cbd5e1; margin:8px 0; }}
ul {{ padding-left:20px; margin:8px 0; }}
li {{ color:#94a3b8; margin:4px 0; }}
a {{ color:#60a5fa; }}
.meta {{ color:#64748b; font-size:0.85em; margin:12px 0 24px; }}
</style></head><body>
<h1>Security Advisory: {data.get('cve_id', '')}</h1>
<div class="meta"><span class="severity">{severity}</span> &nbsp; {data.get('title', '')} | Discovered: {data.get('discovery_date', 'N/A')}</div>

<h2>Description</h2>
<div class="section">{data.get('description', '')}</div>

<h2>Affected Products</h2>
<table><thead><tr><th>Product</th><th>Versions</th><th>Fixed In</th></tr></thead>
<tbody>{products_html}</tbody></table>

<h2>Impact</h2>
<div class="section">{data.get('impact', '')}</div>

<h2>Remediation</h2>
<div class="section">{data.get('remediation', '')}</div>

<h2>References</h2>
<ul>{refs_html}</ul>

<div class="meta" style="margin-top:24px">Generated by JARVIS | {time.strftime('%Y-%m-%d %H:%M UTC')}</div>
</body></html>"""


def executive_summary_html(data: Dict) -> str:
    """Generate an executive summary / board briefing HTML.
    
    data keys: title, date, executive_summary, key_findings, financial_impact,
               risk_assessment, recommendations, next_steps
    """
    findings_html = "".join(f'<li>{f}</li>' for f in data.get("key_findings", []))
    recs_html = "".join(f'<li>{r}</li>' for r in data.get("recommendations", []))
    steps_html = "".join(f'<li>{s}</li>' for s in data.get("next_steps", []))

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>{data.get('title', 'Executive Summary')}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'Segoe UI',system-ui; background:#0f172a; color:#e2e8f0; padding:32px; max-width:900px; margin:0 auto; }}
h1 {{ font-size:1.6em; margin-bottom:8px; }}
h2 {{ color:#60a5fa; margin:20px 0 10px; font-size:1em; border-bottom:1px solid #1e293b; padding-bottom:6px; }}
.section {{ line-height:1.6; color:#cbd5e1; margin:8px 0; }}
ul {{ padding-left:20px; margin:8px 0; }}
li {{ color:#cbd5e1; margin:6px 0; line-height:1.5; }}
.stats {{ display:flex; gap:16px; margin:16px 0; }}
.stat {{ background:#1e293b; padding:16px; border-radius:8px; text-align:center; flex:1; }}
.stat-value {{ font-size:1.4em; font-weight:700; color:#60a5fa; }}
.stat-label {{ font-size:0.75em; color:#64748b; margin-top:4px; }}
.meta {{ color:#64748b; font-size:0.85em; margin:12px 0 24px; }}
</style></head><body>
<h1>{data.get('title', 'Executive Summary')}</h1>
<div class="meta">{data.get('date', time.strftime('%Y-%m-%d'))}</div>

<div class="section">{data.get('executive_summary', '')}</div>

<div class="stats">
{''.join(f'<div class="stat"><div class="stat-value">{v}</div><div class="stat-label">{k}</div></div>' for k, v in data.get('financial_impact', {}).items())}
</div>

<h2>Key Findings</h2>
<ul>{findings_html}</ul>

<h2>Risk Assessment</h2>
<div class="section">{data.get('risk_assessment', '')}</div>

<h2>Recommendations</h2>
<ul>{recs_html}</ul>

<h2>Next Steps</h2>
<ul>{steps_html}</ul>

<div class="meta" style="margin-top:24px">Generated by JARVIS | {time.strftime('%Y-%m-%d %H:%M UTC')}</div>
</body></html>"""


def save_incident(html: str, filename: str, output_dir: str = None) -> str:
    if output_dir is None:
        output_dir = str(Path.home() / "Desktop")
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    filepath = Path(output_dir) / filename
    filepath.write_text(html, encoding="utf-8")
    return str(filepath)
