"""
RF Transmission Staging — Prepares and safely stages raw RF transmission
packets for SDR hardware, with security safety checks and Laser Gate approval.

NO hardcoded app-specific logic. Builds GNU Radio flowgraph .py files
dynamically via file-format synthesis, stages packets in memory,
and requires explicit user approval before any hardware transmission.
"""

import os
import re
import json
import struct
import math
import time
import logging
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class RFPacket:
    """A staged RF transmission packet."""
    frequency: float          # Hz
    modulation: str           # "OOK", "ASK", "FSK", "FM", "AM"
    payload: bytes            # Raw payload bytes
    sample_rate: int          # Output sample rate
    gain: float               # TX gain (dBm)
    bandwidth: int            # Filter bandwidth (Hz)
    metadata: Dict[str, Any]  # Source, timestamp, decoded info


class RFStaging:
    """RF transmission staging and safety management.
    
    Builds GNU Radio flowgraphs dynamically (no hardcoded .grc files),
    stages packets for verification, and enforces Laser Gate approval
    before any hardware transmission.
    """

    def __init__(self):
        self.work_dir = Path(os.path.expanduser("~/JARVIS_Vault/Esoteric/RF"))
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.staged_packets: List[RFPacket] = []
        self.transmission_approved = False
        self.last_payload_hex = ""
        self.flowgraph_path: Optional[str] = None
        self._safety_lock = True  # Lock until approved

    def stage_packet(self, hex_payload: str,
                     frequency: float = 433.92e6,
                     modulation: str = "OOK",
                     sample_rate: int = 2400000,
                     gain: float = 10.0,
                     bandwidth: int = 50000) -> RFPacket:
        """Stage an RF packet for later transmission.
        
        The packet is NOT transmitted — just stored for Laser Gate approval.
        """
        try:
            payload_bytes = bytes.fromhex(hex_payload.replace(" ", "").replace("0x", ""))
        except ValueError as e:
            logger.error(f"Invalid hex payload: {e}")
            payload_bytes = b""

        packet = RFPacket(
            frequency=frequency,
            modulation=modulation,
            payload=payload_bytes,
            sample_rate=sample_rate,
            gain=gain,
            bandwidth=bandwidth,
            metadata={
                "source": "esolang_pipeline",
                "timestamp": time.time(),
                "hex_length": len(hex_payload),
                "decoded": hex_payload[:100],
            }
        )

        self.staged_packets.append(packet)
        self.last_payload_hex = hex_payload[:200] + ("..." if len(hex_payload) > 200 else "")

        logger.info(f"Staged RF packet: {len(payload_bytes)} bytes @ {frequency/1e6:.2f}MHz "
                     f"({modulation}), awaiting Laser Gate approval")

        return packet

    def generate_gnuradio_flowgraph(self, packet: RFPacket,
                                    output_path: str = None) -> str:
        """Generate a GNU Radio flowgraph Python file for the staged packet.
        
        Creates a .py that Gnuradio can execute to modulate and transmit.
        Uses file-format codegen — writes the Python source directly.
        """
        if not output_path:
            output_path = str(self.work_dir / f"rf_flowgraph_{int(time.time())}.py")

        payload_hex = packet.payload.hex()
        payload_list = list(packet.payload)

        # Generate GNU Radio flowgraph for OOK modulation at 433.92MHz
        flowgraph_code = f'''#!/usr/bin/env python3
"""
Auto-generated GNU Radio flowgraph for RF transmission.
Generated by JARVIS RFStaging engine.
"""

import numpy as np
from gnuradio import gr, blocks, analog, filter, eng_notation
from gnuradio.filter import firdes

class rf_transmitter(gr.top_block):
    def __init__(self):
        gr.top_block.__init__(self, "RF Transmitter")

        # Variables
        samp_rate = {packet.sample_rate}
        center_freq = {packet.frequency}
        baud_rate = 4800
        gain = {packet.gain}
        bandwidth = {packet.bandwidth}

        # Payload (bytes)
        payload = bytes({payload_list})

        # Blocks
        self.blocks_vector_source = blocks.vector_source_b(payload, True)
        self.digital_gmsk_mod = analog.gmsk_mod(
            samples_per_symbol=samp_rate // baud_rate,
            sensitivity=0.5,
            BT=0.5,
            gain=1.0,
        )
        self.low_pass_filter = filter.fir_filter_ccf(
            1, firdes.low_pass(1, samp_rate, bandwidth // 2, bandwidth // 4)
        )
        self.blocks_throttle = blocks.throttle(gr.sizeof_gr_complex, samp_rate, True)
        self.analog_const_source = analog.const_source_c(1.0)
        self.analog_amplifier = blocks.multiply_const_cc(0.5)
        self.blocks_head = blocks.head(gr.sizeof_gr_complex, 100000)

        # Connections
        self.connect((self.blocks_vector_source, 0), (self.digital_gmsk_mod, 0))
        self.connect((self.digital_gmsk_mod, 0), (self.low_pass_filter, 0))
        self.connect((self.low_pass_filter, 0), (self.blocks_throttle, 0))
        self.connect((self.blocks_throttle, 0), (self.analog_amplifier, 0))

        # File sink for testing (instead of actual TX)
        self.blocks_file_sink = blocks.file_sink(gr.sizeof_gr_complex, 'rf_output.cfile')
        self.connect((self.analog_amplifier, 0), (self.blocks_file_sink, 0))

        logger.info(f"Flowgraph ready: {{samp_rate}} S/s, {{center_freq/1e6:.2f}}MHz, payload {{len(payload)}} bytes")

def main():
    tb = rf_transmitter()
    tb.start()
    tb.wait()
    logger.info("Transmission complete")

if __name__ == '__main__':
    main()
'''

        with open(output_path, "w") as f:
            f.write(flowgraph_code)

        self.flowgraph_path = output_path
        logger.info(f"Generated GNU Radio flowgraph: {output_path}")

        return output_path

    def verify_packet(self, packet: RFPacket) -> Dict:
        """Perform safety checks on a staged RF packet.
        
        Returns: {safe, issues, freq_legal, payload_risk}
        """
        issues = []

        # Frequency legality check (varies by country — this is for EU/US general ranges)
        freq_mhz = packet.frequency / 1e6
        if freq_mhz < 30 or freq_mhz > 6000:
            issues.append(f"Frequency {freq_mhz:.2f}MHz outside typical legal range")

        # ISM band (most common for hobby use)
        ism_bands = [(433.0, 434.0), (868.0, 868.6), (915.0, 921.0), (2400, 2483.5)]
        in_ism = any(lo <= freq_mhz <= hi for lo, hi in ism_bands)
        if not in_ism:
            issues.append(f"Frequency {freq_mhz:.2f}MHz not in ISM band — verify legality")

        # Payload analysis
        if len(packet.payload) == 0:
            issues.append("Empty payload")
        elif len(packet.payload) > 256:
            issues.append(f"Payload very large ({len(packet.payload)} bytes) — may cause buffer overflow")

        # Check for dangerous patterns (powerful remote control commands)
        danger_words = [b"unlock", b"start", b"engine", b"door", b"gate"]
        for dw in danger_words:
            if dw in packet.payload.lower():
                issues.append(f"Payload contains potentially dangerous command: {dw.decode()}")
                break

        # Gain check
        if packet.gain > 20:
            issues.append(f"High TX gain ({packet.gain}dBm) — may exceed legal EIRP limits")

        return {
            "safe": len(issues) == 0 or all("not in ISM" in i or "outside typical" in i for i in issues),
            "issues": issues,
            "freq_legal": in_ism or len(issues) == 0,
            "payload_risk": "high" if any("dangerous" in i for i in issues) else "low",
        }

    def prepare_transmission(self, packet: RFPacket) -> Dict:
        """Prepare packet for transmission — generates flowgraph but doesn't transmit.
        
        Returns: {flowgraph_path, safe, needs_approval, packet_info}
        """
        fg_path = self.generate_gnuradio_flowgraph(packet)
        verification = self.verify_packet(packet)

        return {
            "flowgraph_path": fg_path,
            "safe": verification["safe"],
            "needs_approval": True,  # Always requires Laser Gate
            "verification": verification,
            "packet_info": {
                "frequency_mhz": packet.frequency / 1e6,
                "modulation": packet.modulation,
                "payload_size": len(packet.payload),
                "payload_hex": packet.payload.hex()[:100],
                "gain": packet.gain,
            }
        }

    def approve_transmission(self, approval_token: str = None) -> bool:
        """Approve transmission (called by Laser Gate when spacebar held 1.5s)."""
        self.transmission_approved = True
        self._safety_lock = False
        logger.info("RF transmission approved by Laser Gate")
        return True

    def execute_transmission(self, packet: RFPacket = None,
                             dry_run: bool = True) -> Dict:
        """Execute RF transmission.
        
        Args:
            packet: packet to transmit (uses last staged if None)
            dry_run: if True, only generates files without actual transmission
            
        Returns: {success, flowgraph, output, error}
        """
        if not self.transmission_approved and not dry_run:
            return {"success": False, "error": "Laser Gate approval required for transmission"}

        if packet is None:
            if not self.staged_packets:
                return {"success": False, "error": "No packet staged"}
            packet = self.staged_packets[-1]

        # Generate flowgraph
        fg_path = self.generate_gnuradio_flowgraph(packet)

        if dry_run:
            return {
                "success": True,
                "flowgraph_path": fg_path,
                "dry_run": True,
                "message": "Packet staged and flowgraph generated. Awaiting Laser Gate approval for real transmission.",
                "packet_info": {
                    "freq_mhz": packet.frequency / 1e6,
                    "payload_hex": packet.payload.hex(),
                    "gain": packet.gain,
                }
            }

        # Real transmission — execute GNU Radio flowgraph
        try:
            result = subprocess.run(
                ["python", fg_path],
                capture_output=True, text=True, timeout=60,
                creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
            )
            return {
                "success": result.returncode == 0,
                "flowgraph_path": fg_path,
                "output": result.stdout,
                "returncode": result.returncode,
                "stderr": result.stderr,
            }
        except Exception as e:
            return {"success": False, "flowgraph_path": fg_path, "error": str(e)}

    def get_staging_status(self) -> Dict:
        """Get current RF staging status."""
        return {
            "packets_staged": len(self.staged_packets),
            "last_payload": self.last_payload_hex,
            "transmission_approved": self.transmission_approved,
            "needs_approval": not self.transmission_approved,
            "flowgraph_path": self.flowgraph_path,
            "safety_lock_active": self._safety_lock,
        }


# Module-level singleton
_rf_staging = None

def get_rf_staging() -> RFStaging:
    global _rf_staging
    if _rf_staging is None:
        _rf_staging = RFStaging()
    return _rf_staging
